"""Incluindo o campo respondido na tabela

Revision ID: fea723575263
Revises: 8c443f21d0de
Create Date: 2024-07-28 15:54:13.516741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea723575263'
down_revision = '8c443f21d0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contatos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondido', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contatos', schema=None) as batch_op:
        batch_op.drop_column('respondido')

    # ### end Alembic commands ###
